### ISSUE TITLE
Discussion for proposal question regarding use of PCL_EXPORT

### ISSUE THREAD

**Issue by divmadan** [divmadan/pcl#2]
### Reference Topic: 
OpenCV-Python
### Point of discussion: 
The header parser doesn't parse all the functions/classes in the header file. The developer has to specify which functions should be exported to Python. For that, **there are certain macros added to the beginning of these declarations** which enables the header parser to identify functions to be parsed.
### Proposal question: 
"Would modifications to PCL_EXPORT be sufficient for this?"
### Discussion so far:
@divmadan 
> Yes.
> 
> OpenCV coding guidelines:
> "All public functions and classes must be marked with the CV_EXPORTS macro. CV_EXPORTS_W macro should be used to expose class or function to Python and Java bindings."
> 
> CV_EXPORTS_W is an alias for CV_EXPORT which is an alias for `__declspec(dllexport)`, similar to PCL case.
> 
> If we already have marked public functions and classes with PCL_EXPORTS (which I guess we have), we can follow a similar approach as OpenCV.
> 
> I don't think we will need to modify the macro, it is for use as an indicator. Correct me if I'm wrong.
> 
> -------
> 
> Also, they use many other macros for handling methods, overloaded functions, structs. Have a look here:
> 
> https://opencv24-python-tutorials.readthedocs.io/en/latest/py_tutorials/py_bindings/py_bindings_basics/py_bindings_basics.html#how-to-extend-new-modules-to-python
> 
> (copy, paste, links not supported in comments)
> 
> Can you give your opinion as to will it be doable, if it should be done?

@kunaltyagi
> Using libtooling might be something to look into if we need to touch every data member and virtual function/overloads. But that discussion is not for here :)

**Comment by divmadan** [comment]
@kunaltyagi

I used the header parser in this repo: https://github.com/baszalmstra/header-parser on our [keypoint.h](https://github.com/PointCloudLibrary/pcl/blob/master/2d/include/pcl/2d/keypoint.h) file after adding some identifiers:

<details>
<summary>Modifications</summary>

```

#pragma once

#include <pcl/2d/edge.h>

namespace pcl {

TCLASS()
class Keypoint {
private:
  Edge edge_detection;
  Convolution conv_2d;

public:
  Keypoint() {}

  TFUNC()
  void
  harrisCorner(ImageType& output,
               ImageType& input,
               const float sigma_d,
               const float sigma_i,
               const float alpha,
               const float thresh);

  TFUNC()
  void
  hessianBlob(ImageType& output, ImageType& input, const float sigma, bool SCALE);

  TFUNC()
  void
  hessianBlob(ImageType& output,
              ImageType& input,
              const float start_scale,
              const float scaling_factor,
              const int num_scales);

  TFUNC()
  void
  imageElementMultiply(ImageType& output, ImageType& input1, ImageType& input2);
};

} // namespace pcl

#include <pcl/2d/impl/keypoint.hpp>
```
</details>


The results are promising and just what we need:
<details>
<summary>JSON Output</summary>

```
[
    {
        "type": "include",
        "file": "pcl/2d/edge.h"
    },
    {
        "type": "namespace",
        "name": "pcl",
        "members": [
            {
                "type": "class",
                "line": 48,
                "meta": {},
                "isstruct": false,
                "name": "Keypoint",
                "members": [
                    {
                        "type": "function",
                        "macro": "TFUNC",
                        "line": 57,
                        "meta": {},
                        "access": "public",
                        "returnType": {
                            "type": "literal",
                            "name": "void"
                        },
                        "name": "harrisCorner",
                        "arguments": [
                            {
                                "type": {
                                    "type": "reference",
                                    "baseType": {
                                        "type": "literal",
                                        "name": "ImageType"
                                    }
                                },
                                "name": "output"
                            },
                            {
                                "type": {
                                    "type": "reference",
                                    "baseType": {
                                        "type": "literal",
                                        "name": "ImageType"
                                    }
                                },
                                "name": "input"
                            },
                            {
                                "type": {
                                    "const": true,
                                    "type": "literal",
                                    "name": "float"
                                },
                                "name": "sigma_d"
                            },
                            {
                                "type": {
                                    "const": true,
                                    "type": "literal",
                                    "name": "float"
                                },
                                "name": "sigma_i"
                            },
                            {
                                "type": {
                                    "const": true,
                                    "type": "literal",
                                    "name": "float"
                                },
                                "name": "alpha"
                            },
                            {
                                "type": {
                                    "const": true,
                                    "type": "literal",
                                    "name": "float"
                                },
                                "name": "thresh"
                            }
                        ]
                    },
                    {
                        "type": "function",
                        "macro": "TFUNC",
                        "line": 66,
                        "meta": {},
                        "access": "public",
                        "returnType": {
                            "type": "literal",
                            "name": "void"
                        },
                        "name": "hessianBlob",
                        "arguments": [
                            {
                                "type": {
                                    "type": "reference",
                                    "baseType": {
                                        "type": "literal",
                                        "name": "ImageType"
                                    }
                                },
                                "name": "output"
                            },
                            {
                                "type": {
                                    "type": "reference",
                                    "baseType": {
                                        "type": "literal",
                                        "name": "ImageType"
                                    }
                                },
                                "name": "input"
                            },
                            {
                                "type": {
                                    "const": true,
                                    "type": "literal",
                                    "name": "float"
                                },
                                "name": "sigma"
                            },
                            {
                                "type": {
                                    "type": "literal",
                                    "name": "bool"
                                },
                                "name": "SCALE"
                            }
                        ]
                    },
                    {
                        "type": "function",
                        "macro": "TFUNC",
                        "line": 70,
                        "meta": {},
                        "access": "public",
                        "returnType": {
                            "type": "literal",
                            "name": "void"
                        },
                        "name": "hessianBlob",
                        "arguments": [
                            {
                                "type": {
                                    "type": "reference",
                                    "baseType": {
                                        "type": "literal",
                                        "name": "ImageType"
                                    }
                                },
                                "name": "output"
                            },
                            {
                                "type": {
                                    "type": "reference",
                                    "baseType": {
                                        "type": "literal",
                                        "name": "ImageType"
                                    }
                                },
                                "name": "input"
                            },
                            {
                                "type": {
                                    "const": true,
                                    "type": "literal",
                                    "name": "float"
                                },
                                "name": "start_scale"
                            },
                            {
                                "type": {
                                    "const": true,
                                    "type": "literal",
                                    "name": "float"
                                },
                                "name": "scaling_factor"
                            },
                            {
                                "type": {
                                    "const": true,
                                    "type": "literal",
                                    "name": "int"
                                },
                                "name": "num_scales"
                            }
                        ]
                    },
                    {
                        "type": "function",
                        "macro": "TFUNC",
                        "line": 78,
                        "meta": {},
                        "access": "public",
                        "returnType": {
                            "type": "literal",
                            "name": "void"
                        },
                        "name": "imageElementMultiply",
                        "arguments": [
                            {
                                "type": {
                                    "type": "reference",
                                    "baseType": {
                                        "type": "literal",
                                        "name": "ImageType"
                                    }
                                },
                                "name": "output"
                            },
                            {
                                "type": {
                                    "type": "reference",
                                    "baseType": {
                                        "type": "literal",
                                        "name": "ImageType"
                                    }
                                },
                                "name": "input1"
                            },
                            {
                                "type": {
                                    "type": "reference",
                                    "baseType": {
                                        "type": "literal",
                                        "name": "ImageType"
                                    }
                                },
                                "name": "input2"
                            }
                        ]
                    }
                ]
            }
        ]
    },
    {
        "type": "include",
        "file": "pcl/2d/impl/keypoint.hpp"
    }
]
```
</details>

Tools such as CastXML requires building the source to generate XML parse-tree, and that isn't really needed. A header parsing script will be enough and better for binding-generation, that's why I don't want to use those.

I also modified the OpenCV header parser, to see if it can fit our use case, although some work still needs to be done to generate proper results.

I wanted to know your initial views on the output generated and the modifications in the header file, and the use of the header parser repo https://github.com/baszalmstra/header-parser in our project.

In the meantime, I'll try parsing other complex headers using it and continue the modifications of the OpenCV parser.

P.S: As mentioned in the README:
> This library is currently used in production at Abbey Games to generate extensive C++ Lua bindings and documentation for internal use.

**Comment by kunaltyagi** [comment]
> after adding some identifiers

That's a slight issue when the library is already huge. A compilation based approach might be more complicated, but will touch less lines.

> will be enough and better for binding-generation

I understand about the `enough` aspect, but could you explain a bit on why it is also better than a compilation based approach?

**Comment by divmadan** [comment]
> That's a slight issue when the library is already huge. A compilation based approach might be more complicated, but will touch less lines.

That's true, although the identifier based approach also gives us control over what classes, functions. etc. to expose and what not to. I guess that's also part of the reason why we decided to use PCL_EXPORTS in the first place and not just generate bindings for all.

> I understand about the enough aspect, but could you explain a bit on why it is also better than a compilation based approach?

- On top of my head, it will definitely be fast (as it is just performing file operation and string manipulation), very light (just some scripts) and gives control over what to expose.
- OpenCV has a python script, vtk has lex and yacc parser, pclpy uses cppheaderparser. The general approach to binding generation has been parsing as opposed to compiling.
- If we want conditional bindings generation (expose some, exclude others), compiling will be way slower during prototyping.
- Also, parsing approach doesn't need cpp files. I don't know if this is a plus point, but since we have a nice structure with all header files, I think header parsing is the way to go.
- Why do we need to compile the library? pybind11 only requires classes and their declarations, which are available in the header files.

Am I missing something? Would love some insight.
Also, did you take a look at that repo?

**Comment by kunaltyagi** [comment]
> identifier based approach also gives us control over what classes, functions. etc. to expose and what not to

We're already doing that via `PCL_EXPORTS`. Having more fine grained control isn't needed (since we can export non-template classes, functions and enums. Member functions get the default visibility, templates have to be exported)

> Also, did you take a look at that repo?

Yeah. Not the code though.

> Am I missing something?

Maybe how to handle dependencies: I don't know if parsing addresses this, though looking at the include list in the json, I think it does.

**Comment by divmadan** [comment]
What do you suggest is the way forward? Need some guidance.

I'll continue experimenting with the above method, but I don't want to waste lots of time if we can't use it.

**Comment by kunaltyagi** [comment]
I've started an experiment with something, but it's too soon to say. Sadly, it'll take me time to check if my approach works (and is "decent").

**Comment by divmadan** [comment]
Are you trying out something with libtooling? :thinking:

**Comment by divmadan** [comment]
@kunaltyagi 
If you have time, have a look at this:
https://github.com/divmadan/pybind11-generator/blob/master/template_strings.py

I have just started that, largerly incomplete, a lot left to do.
While we figure out whether to use parsing or libtooling, parallelly I can work on a script to convert the classes and its attributes into pybind11 code. I'm trying the automation for JSON files https://github.com/divmadan/pcl/issues/2#issuecomment-615273426, but we can edit that or use it as a reference, should we choose to go with libtooling's AST representation (and whatever way we represent it after cursors etc.)

Also, please feel free to leave comments about anything you feel like.

**Comment by kunaltyagi** [comment]
It'll take some time. Bit busy nowadays

**Comment by kunaltyagi** [comment]
I'm sorry, but could you please explain a bit about the role of the file? The file by itself gives very little information.

Also, I managed to get all the definitions in a file using libtooling (and the `compile_commands.yaml` but I'm putting the experiment on hold till the 1.11 release)

**Comment by divmadan** [comment]
Yeah, sorry about that. That file is a helper file which stores the template strings for various pybind11 statements, like class declaration, constructor initialisation, function declaration, etc.

A script will then take the definitions generated by libtooling or a parser, and write corresponding pybind11 code to `generated_binding_file.cpp`, with the help of that template string file, resulting in binding-generation automation.

Using template was the initial choice that came to my mind, and I just started compiling pybind11 statements. That **list** will be required, in whatever form, eventually.

Instead of a python script, that task might be good to perform using c++ if we use libtooling. I don't yet know the capabilities of code-generation using libtooling, as in whether using only libtooling, we can generate pybind11 code.

Here is the [repo](https://github.com/divmadan/pybind11-generator), although I haven't worked on the script, that's why I didn't share. Sorry about that.


> Also, I managed to get all the definitions in a file using libtooling

I thought you were the mentor :rofl:
JK, please share.

**Comment by kunaltyagi** [comment]
> I thought you were the mentor

Yes, but I should get a test working before saying "this is the way". The code is pretty simple, the difficult part was getting the time and LLVM for working on it. I'd actually recommend you to experiment with different ast parsers and accessors if this approach is chosen rather than copy my hack (I discovered some techniques a bit too late and didn't want to rewrite the complete thing)

I'll look at the repo (and your comment) later
